esphome:
  name: esp32bt01
  friendly_name: esp32bt01

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "CpKAZOk3F4DDK+hG17E+qZLi9xcUIzKG6HFgOcPdwVM="

ota:
  password: "568db6dc76bff7c229d68360ed0796d3"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32Bt01 Fallback Hotspot"
    password: "lrtrdZMgsQPu"

captive_portal:
    
esp32_ble_tracker:
  scan_parameters:
    active: true
    interval: 1100ms
    window: 1100ms
    
bluetooth_proxy:  