esphome:
  name: greenhouse
  friendly_name: greenhouse

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "ovMCgvBO9b0+13xy5p6Wm9WWo023N1/rNEoD8538wvQ="

ota:
  password: "d6bf3e5da3c42eb8098632b35ed3f9f9"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Greenhouse Fallback Hotspot"
    password: "uqp6d5cOKPiP"

captive_portal:
    
dallas:
  - pin: GPIO14

sensor:
  - platform: adc
    pin: VCC
    name: "greenhouse_battery"
    force_update: true
    accuracy_decimals: 2  
    
  - platform: dallas
    name: "greenhouse_temperature"
    address: "0xc70319a2792fe328"
    force_update: true
    accuracy_decimals: 2
    filters:
    - offset: 0.2
    
  - platform: dallas
    name: "greenhouse_outdoor_temperature"
    address: "0x890316a279018928"
    force_update: true
    accuracy_decimals: 2
    filters:
    - offset: 0.6