esphome:
  name: kjellerkontoret
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Kjellerkontoret Fallback Hotspot"
    password: "SZbnJWQh2MAT"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "ronny"

ota:
  password: "ronny"

dallas:
  - pin: D5
    update_interval: 60s

sensor:
  - platform: dallas
    name: "Kjellerkontor temperatur"
    address: "0x913C01A816738C28"
    accuracy_decimals: 2

  - platform: adc
    pin: VCC
    name: "Kjellerkontor batteri"
    update_interval: 60s
    accuracy_decimals: 2