sensor:
  - platform: integration
    source: sensor.garage_freezer_power
    name: garage_freezer_energy
    unique_id: garage_freezer_energy
    round: 2
    method: left
    unit_prefix: k

  - platform: history_stats
    name: garage_freezer_runtime_today
    entity_id: sensor.garage_freezer_running
    state: "True"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"

template:
  - sensor:
    - name: garage_freezer_power
      unique_id: garage_freezer_power
      device_class: power
      state: >-
        {% if states('sensor.garage_freezer_plug_power') | float(0) < 0 %}
          0
        {% else %}
          {{ states('sensor.garage_freezer_plug_power') | float(0) }}
        {% endif %}
      unit_of_measurement: W

    - name: "Garage Freezer running"
      unique_id : garage_freezer_running
      state: "{{ states('sensor.garage_freezer_power') | float(0) > 10 }}"

utility_meter:
  garage_freezer_daily_energy:
    source: sensor.garage_freezer_energy
    name: garage_freezer_daily_energy
    unique_id: garage_freezer_daily_energy
    cycle: daily

  garage_freezer_monthly_energy:
    source: sensor.garage_freezer_energy
    name: garage_freezer_monthly_energy
    unique_id: garage_freezer_monthly_energy
    cycle: monthly

  garage_freezer_yearly_energy:
    source: sensor.garage_freezer_energy
    name: garage_freezer_yearly_energy
    unique_id: garage_freezer_yearly_energy
    cycle: yearly