automation:
  - id: "porch_light_on"
    alias: _Vindfang - Lys på
    description: ""
    trigger:
      - platform: sun
        event: sunset
      - type: motion
        platform: device
        device_id: 383c3182c3711318539ab7108ccc3f04
        entity_id: binary_sensor.porch_motion_occupancy
        domain: binary_sensor
    condition: []
    action:
      - service: light.turn_on
        target:
          entity_id:
            - light.porch_light
        data:
          brightness_pct: 50
          transition: 1
    mode: single

  - id: "porch_light_off"
    alias: _Vindfang - Lys av
    description: ""
    trigger:
      - type: no_motion
        platform: device
        device_id: 383c3182c3711318539ab7108ccc3f04
        entity_id: binary_sensor.porch_motion_occupancy
        domain: binary_sensor
        for:
          hours: 0
          minutes: 15
          seconds: 0
          milliseconds: 0
      - platform: time
        at: 00:00
    condition: []
    action:
      - choose:
          - conditions:
              - condition: time
                after: 00:00
                before: 06:00
            sequence:
              - service: light.turn_off
                target:
                  entity_id:
                    - light.porch_light
                data:
                  transition: 1
        default:
          - service: light.turn_on
            target:
              entity_id:
                - light.porch_light
            data:
              transition: 2
              brightness_pct: 15
    mode: restart
